#!/usr/bin/env python3
"""Stop MoltenVK's gen_moltenvk_rev_hdr.sh from inheriting the parent monorepo SHA.

The script runs `git rev-parse HEAD` with no GIT_DIR. Inside Cyder/ogom that
records the app/engine commit instead of a MoltenVK revision. Rewrite it to
emit the pure MVK_VERSION_STRING from the API headers (e.g. 1.2.10).
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

SCRIPT_REL = Path("Scripts/gen_moltenvk_rev_hdr.sh")
VERSION_HEADER_CANDIDATES = (
    Path("MoltenVK/MoltenVK/API/mvk_private_api.h"),
    Path("MoltenVK/MoltenVK/API/mvk_config.h"),
)


def read_mvk_version_string(source: Path) -> str:
    for rel in VERSION_HEADER_CANDIDATES:
        path = source / rel
        if not path.is_file():
            continue
        text = path.read_text(encoding="utf-8", errors="replace")
        majors = re.search(r"#define\s+MVK_VERSION_MAJOR\s+(\d+)", text)
        minors = re.search(r"#define\s+MVK_VERSION_MINOR\s+(\d+)", text)
        patchs = re.search(r"#define\s+MVK_VERSION_PATCH\s+(\d+)", text)
        if majors and minors and patchs:
            return f"{majors.group(1)}.{minors.group(1)}.{patchs.group(1)}"
        # Already-expanded string form (unlikely in headers).
        m = re.search(r'#define\s+MVK_VERSION_STRING\s+"([^"]+)"', text)
        if m:
            return m.group(1)
    return "crossover-snapshot"


def render_script(version: str) -> str:
    return (
        "#!/bin/bash\n"
        "# Cyder: pin rev string to MVK version — avoid inheriting monorepo HEAD.\n"
        f'MVK_GIT_REV="{version}"\n'
        'MVK_HDR_FILE="${BUILT_PRODUCTS_DIR}/mvkGitRevDerived.h"\n'
        'echo "// Auto-generated by MoltenVK (Cyder-pinned)" > "${MVK_HDR_FILE}"\n'
        'echo "static const char* mvkRevString = \\"${MVK_GIT_REV}\\";" >> "${MVK_HDR_FILE}"\n'
    )


def pin_moltenvk_source(source: Path) -> str:
    script = source / SCRIPT_REL
    if not script.is_file():
        raise FileNotFoundError(f"missing {script}")
    version = read_mvk_version_string(source)
    new_text = render_script(version)
    old = script.read_text(encoding="utf-8")
    if old != new_text:
        script.write_text(new_text, encoding="utf-8")
        script.chmod(script.stat().st_mode | 0o111)
    return version


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("source", type=Path, help="Path to extracted sources/moltenvk")
    args = parser.parse_args(argv)
    try:
        version = pin_moltenvk_source(args.source.resolve())
    except (OSError, ValueError) as exc:
        print(f"pin-moltenvk-git-rev: {exc}", file=sys.stderr)
        return 1
    print(version)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
